### ISSUE TITLE
The get_config returns duplicated items

### ISSUE THREAD

**Issue by ycliuhw** [juju-solutions/interface-oidc-client#1]
The get_config returns two same items:

```yaml
staticClients:
- id: authservice-oidc
  name: Ambassador Auth OIDC
  redirectURIs:
  - http://10.64.140.43.xip.io:80/oidc/login/oidc
  secret: OSOWLY2T2OUECRFEN43IT9O8D1UXD0
- id: authservice-oidc
  name: Ambassador Auth OIDC
  redirectURIs:
  - http://10.64.140.43.xip.io:80/oidc/login/oidc
  secret: OSOWLY2T2OUECRFEN43IT9O8D1UXD0

```

It seems the `endpoint_from_name('oidc-client').get_config(unit_name)` should have an unit arg.
```python
def get_config(self, unit_name):
        return [
            json.loads(unit.received_raw["client_info"])
            for relation in self.relations
            for unit in relation.joined_units
            if unit. unit_name == unit_name
            if unit.received_raw.get('client_info')
        ]
```

Or it's the problem of the `config()` in the provider side.
